/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Vishal Yadav
 */
public class TicTacToeGame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TicTacToeGame.class.getName());

    /**
     * Creates new form TicTacToeGame
     */
    String playerX, playerO;
    boolean xTurn = true;
    javax.swing.JButton[][] buttons = new javax.swing.JButton[3][3];
    javax.swing.JLabel turnLabel;
    public TicTacToeGame() {
        initComponents();
        StartBtn.addActionListener(e -> startGame());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
        private void startGame() {
    playerX = XTF.getText();
    playerO = OTF.getText();

    if (playerX.isEmpty() || playerO.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Enter both player names!");
        return;
    }

    createGameBoard();
}
        private void createGameBoard() {
    javax.swing.JFrame gameFrame = new javax.swing.JFrame("Tic Tac Toe");
    gameFrame.setSize(400, 450);
    gameFrame.setLayout(new java.awt.BorderLayout());

    // Turn label
    turnLabel = new javax.swing.JLabel(playerX + "'s Turn (X)", javax.swing.SwingConstants.CENTER);
    gameFrame.add(turnLabel, java.awt.BorderLayout.NORTH);

    // Grid panel
    javax.swing.JPanel panel = new javax.swing.JPanel();
    panel.setLayout(new java.awt.GridLayout(3, 3));

    for (int i = 0; i < 3; i++) {
        for (int j = 0; j < 3; j++) {
            buttons[i][j] = new javax.swing.JButton("");
            buttons[i][j].setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 40));

            int row = i, col = j;

            buttons[i][j].addActionListener(e -> handleMove(row, col));

            panel.add(buttons[i][j]);
        }
    }

    gameFrame.add(panel, java.awt.BorderLayout.CENTER);

    gameFrame.setVisible(true);
}
        private void handleMove(int i, int j) {
    if (!buttons[i][j].getText().equals("")) return;

    if (xTurn) {
        buttons[i][j].setText("X");
        turnLabel.setText(playerO + "'s Turn (O)");
    } else {
        buttons[i][j].setText("O");
        turnLabel.setText(playerX + "'s Turn (X)");
    }

    xTurn = !xTurn;

    checkWinner();
}   
     private void checkWinner() {
    String[][] board = new String[3][3];
    boolean isDraw = true;
    boolean winnerFound = false;

    // Fill board & check empty cells
    for (int i = 0; i < 3; i++) {
        for (int j = 0; j < 3; j++) {
            board[i][j] = buttons[i][j].getText();
            if (board[i][j].equals("")) {
                isDraw = false;
            }
        }
    }

    // Check rows & columns
    for (int i = 0; i < 3; i++) {
        if (!board[i][0].equals("") &&
            board[i][0].equals(board[i][1]) &&
            board[i][1].equals(board[i][2])) {
            showWinner(board[i][0]);
            winnerFound = true;
            return;
        }

        if (!board[0][i].equals("") &&
            board[0][i].equals(board[1][i]) &&
            board[1][i].equals(board[2][i])) {
            showWinner(board[0][i]);
            winnerFound = true;
            return;
        }
    }

    // Diagonals
    if (!board[0][0].equals("") &&
        board[0][0].equals(board[1][1]) &&
        board[1][1].equals(board[2][2])) {
        showWinner(board[0][0]);
        winnerFound = true;
        return;
    }

    if (!board[0][2].equals("") &&
        board[0][2].equals(board[1][1]) &&
        board[1][1].equals(board[2][0])) {
        showWinner(board[0][2]);
        winnerFound = true;
        return;
    }

    // ✅ ONLY check draw if NO winner
    if (!winnerFound && isDraw) {
        showDraw();
    }
}
      private void showDraw() {
      disableBoard(); // stop game

    javax.swing.JOptionPane.showMessageDialog(
        this,"😃 Match Draw!");

    resetGame();
}
      private void showWinner(String winnerSymbol) {
    String winnerName = winnerSymbol.equals("X") ? playerX : playerO;

    disableBoard(); // stop further clicks

    javax.swing.JOptionPane.showMessageDialog(
        this,
        "🎉 Congratulations " + winnerName + " Wins!"
    );

    resetGame();
}
      private void disableBoard() {
    for (int i = 0; i < 3; i++) {
        for (int j = 0; j < 3; j++) {
            buttons[i][j].setEnabled(false);
        }
    }
}
   private void resetGame() {
    for (int i = 0; i < 3; i++) {
        for (int j = 0; j < 3; j++) {
            buttons[i][j].setText("");
            buttons[i][j].setEnabled(true); // IMPORTANT
        }
    }

    xTurn = true;
    turnLabel.setText(playerX + "'s Turn (X)");
}
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        XName = new javax.swing.JLabel();
        OName = new javax.swing.JLabel();
        XTF = new javax.swing.JTextField();
        OTF = new javax.swing.JTextField();
        StartBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        XName.setText("Enter Player X Name :");

        OName.setText("Enter Player O Name :");

        StartBtn.setBackground(new java.awt.Color(0, 0, 255));
        StartBtn.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        StartBtn.setText("Start");

        jLabel1.setBackground(new java.awt.Color(255, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Tic Tac Toe Game");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(StartBtn)
                .addGap(145, 145, 145))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(OName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(OTF))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(XName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(XTF, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(XName)
                    .addComponent(XTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OName)
                    .addComponent(OTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(StartBtn)
                .addContainerGap(93, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TicTacToeGame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel OName;
    private javax.swing.JTextField OTF;
    private javax.swing.JButton StartBtn;
    private javax.swing.JLabel XName;
    private javax.swing.JTextField XTF;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
